FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Presentation.Web/Presentation.Web.csproj", "Presentation.Web/"]
COPY ["src/Application/Application.csproj", "Application/"]
COPY ["src/Domain/Domain.csproj", "Domain/"]
COPY ["src/Infrastructure/Infrastructure.csproj", "Infrastructure/"]

RUN dotnet restore "Presentation.Web/Presentation.Web.csproj"

COPY . .

WORKDIR "/src/Presentation.Web"
RUN dotnet build "Presentation.Web.csproj" -c Release -o /app/build

# Publicar
FROM build AS publish
RUN dotnet publish "Presentation.Web.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Presentation.Web.dll"]